apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sad-kistpay-cert
  namespace: default
spec:
  secretName: sad-kistpay-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sad-kistpay.com
  dnsNames:
  - sad-kistpay.com
