apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: service1-backendconfig
  namespace: namespace1
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  securityPolicy:
    name: "service1-security-policy"
  rateLimit:
    name: "service1-rate-limit"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: service2-backendconfig
  namespace: namespace2
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  securityPolicy:
    name: "service2-security-policy"
  rateLimit:
    name: "service2-rate-limit"
