apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: namespace1
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "service1-backendconfig"}'
    #cloud.google.com/app-protocols: '{"my-service":"HTTP"}'
    #cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: service1
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: namespace2
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "service2-backendconfig"}'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: service2
